version: '3.8'
services:
  mysql:
    image: mysql:8.0  # Cambia a la versión que estés usando
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Desde tu archivo .env
      MYSQL_DATABASE: ${DATABASE_NAME}     # Desde tu archivo .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  app:
    build: .
    container_name: node_app
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_PORT: 3306
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - mysql

volumes:
  db_data:

networks:
  my_network:
